[package]
name = "asset-importer-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.21.0", features = ["derive"] }
enumflags2 = "0.7.10"
gltf = { version = "1.4.1", optional = true, features = ["extensions"] }
gltf-v1 = { path = "gltf-v1", optional = true, version = "0.1.0" }
serde = "1.0.217"
serde_derive = "1.0.217"
serde_json = "1.0.134"

[features]
default = [
    "use_gltf_2",
    "use_gltf_1",
    "KHR_texture_transform",
    "KHR_materials_unlit",
    "KHR_materials_transmission",
    "KHR_materials_ior",
    "KHR_materials_volume",
    "KHR_materials_specular",
    "KHR_materials_pbrSpecularGlossiness",
    "KHR_materials_emissive_strength",
    "KHR_materials_ior",
]

use_double_precision = []
use_gltf_1 = ["dep:gltf-v1"]
use_gltf_2 = ["dep:gltf"]

KHR_texture_transform = ["gltf/KHR_texture_transform"]
KHR_materials_unlit = ["gltf/KHR_materials_unlit"]
KHR_materials_transmission = ["gltf/KHR_materials_transmission"]
KHR_materials_ior = ["gltf/KHR_materials_ior"]
KHR_materials_volume = ["gltf/KHR_materials_volume"]
KHR_materials_specular = ["gltf/KHR_materials_specular"]
KHR_materials_pbrSpecularGlossiness = [
    "gltf/KHR_materials_pbrSpecularGlossiness",
]
KHR_materials_emissive_strength = ["gltf/KHR_materials_emissive_strength"]
