[package]
name = "asset-importer-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
enumflags2 = "0.7.10"
gltf = { version="1.4.1", optional = true}
serde = "1.0.217"
serde_derive = "1.0.217"
serde_json = "1.0.134"

[features]
default = ["use_gltf"]

use_double_precision = []
use_gltf = ["dep:gltf"]
