[package]
name = "asset-importer-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.21.0", features = ["derive"] }
enumflags2 = "0.7.10"
gltf = { version = "1.4.1", optional = true }
gltf-v1 = { path = "gltf-v1", optional = true, version = "0.1.0" }
image = { version = "0.25.5", features = [
    "png",
    "jpeg",
    "webp"
], default-features = false }
num_enum = "0.7.3"
serde = "1.0.217"
serde_derive = "1.0.217"
serde_json = "1.0.134"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false

[features]
minimal = ["asset_gltf_v2"]

default = [
    "asset_gltf_v2",
    "asset_gltf_v1",
    "gltf_extensions",
    "KHR_texture_transform",
    "KHR_materials_unlit",
    "KHR_materials_transmission",
    "KHR_materials_ior",
    "KHR_materials_volume",
    "KHR_materials_specular",
    "KHR_materials_pbrSpecularGlossiness",
    "KHR_materials_emissive_strength",
    "KHR_materials_ior",
    "KHR_lights_punctual",
]

use_double_precision = []

asset_gltf_v1 = ["dep:gltf-v1"]

#GLTF 2.0 Extensions
asset_gltf_v2 = ["dep:gltf"]

gltf_extensions = ["gltf/extensions"]
KHR_texture_transform = ["gltf/KHR_texture_transform"]
KHR_materials_unlit = ["gltf/KHR_materials_unlit"]
KHR_materials_transmission = ["gltf/KHR_materials_transmission"]
KHR_materials_ior = ["gltf/KHR_materials_ior"]
KHR_materials_volume = ["gltf/KHR_materials_volume"]
KHR_materials_specular = ["gltf/KHR_materials_specular"]
KHR_materials_pbrSpecularGlossiness = [
    "gltf/KHR_materials_pbrSpecularGlossiness",
]
KHR_materials_emissive_strength = ["gltf/KHR_materials_emissive_strength"]
KHR_lights_punctual = ["gltf/KHR_lights_punctual"]
# gltf_EXT_texture_webp = ["gltf/EXT_texture_webp", "image/webp"]
