[package]
name = "asset-importer-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = {version = "1.21.0", features = ["derive"]}
enumflags2 = "0.7.10"
gltf = { version="1.4.1", optional = true}
gltf-v1 = { path="gltf-v1", optional = true, version ="0.1.0"}
serde = "1.0.217"
serde_derive = "1.0.217"
serde_json = "1.0.134"

[features]
default = ["use_gltf_2", "use_gltf_1", "KHR_texture_transform"] 

use_double_precision = []
use_gltf_1 = ["dep:gltf-v1"]
use_gltf_2 = ["dep:gltf"]

KHR_texture_transform = ["gltf/KHR_texture_transform"]
