[package]
name = "asset-importer-rs-dae"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}
description = "DAE (Collada) importer for asset-importer-rs"
license = {workspace = true}
repository = {workspace = true}
documentation = "https://docs.rs/asset-importer-rs-dae"

[dependencies]
asset-importer-rs-core = {workspace = true}
asset-importer-rs-scene = {workspace = true}
dae-parser = {workspace = true}
enumflags2 = {workspace = true}
bytemuck = {workspace = true}

[features]
default = []
