pub const AI_CONFIG_CHECK_IDENTITY_MATRIX_EPSILON: &str = "CHECK_IDENTITY_MATRIX_EPSILON";
pub const AI_CONFIG_CHECK_IDENTITY_MATRIX_EPSILON_DEFAULT: f32 = 10e-3f32;
pub const AI_CONFIG_USE_GLTF_PBR_SPECULAR_GLOSSINESS: &str = "USE_GLTF_PBR_SPECULAR_GLOSSINESS";