use crate::structs::base_types::AiReal;

pub const AI_CONFIG_CHECK_IDENTITY_MATRIX_EPSILON: &str = "CHECK_IDENTITY_MATRIX_EPSILON";
pub const AI_CONFIG_CHECK_IDENTITY_MATRIX_EPSILON_DEFAULT: AiReal = 10e-3f32 as AiReal;
pub const AI_CONFIG_USE_GLTF_PBR_SPECULAR_GLOSSINESS: &str = "USE_GLTF_PBR_SPECULAR_GLOSSINESS";
pub const GLTF2_NODE_IN_TRS: &str = "GLTF2_NODE_IN_TRS";
pub const AI_CONFIG_EXPORT_GLTF_UNLIMITED_SKINNING_BONES_PER_VERTEX: &str = "AI_CONFIG_EXPORT_GLTF_UNLIMITED_SKINNING_BONES_PER_VERTEX";
pub const GLTF2_TARGET_NORMAL_EXP: &str = "GLTF2_TARGET_NORMAL_EXP";