name: Security Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-audit:
    name: Cargo Audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - uses: taiki-e/install-action@dbd64b376a77edb5c67164dc7b5383735171cf97 # cargo-audit
        with:
          tool: cargo-audit
      - name: Audit
        run: cargo audit
