name: Benchmarks

on:
    push:
        branches:
        - master

permissions:
    contents: write
    deployments: write

jobs:
  benchmark:
    name: Run Rust benchmark example
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run benchmark
          run: cargo bench | tee output.txt
        - name: Store benchmark result
          uses: benchmark-action/github-action-benchmark@v1
          with:
            name: Rust Benchmark
            tool: 'cargo'
            output-file-path: output.txt
            github-token: ${{ secrets.GITHUB_TOKEN }}
            auto-push: true
            alert-threshold: '120%'
            comment-on-alert: true
            fail-on-alert: true
            alert-comment-cc-users: '@crazyjackel'        